//! Adversarial / degenerate FASTQ inputs that probe the u32 per-column byte
//! limit of the StringPod columnar layout (positions are u32, so any single
//! column — hence any single read line — is capped at 4 GiB).
//!
//! Fixtures live in `tests/adversarial/` and are regenerated by `gen.py`.
//!
//!  * `more_than_64_mb_after_expansion.fastq.gz` — ~65 MiB of small (256-base)
//!    reads. Exceeds the pipeline's 64 MiB speculative reservation but stays
//!    well under u32::MAX, so it must decode *correctly*. A regression guard
//!    for the "chunk expands past the reservation" path.
//!
//!  * `4gb_plus_read.fastq.gz` — a single read longer than u32::MAX bytes. Must
//!    fail with a clean "FASTQ read length exceeds the allowed maximum of 4 GiB"
//!    error instead of panicking in the u32 cast (the original bug). This test
//!    is `#[ignore]`d because it decodes ~4 GiB and needs several GiB of RAM;
//!    run it explicitly (see the test's doc comment).

use std::path::PathBuf;
use std::thread;

use crossbeam_channel::bounded;
use rusty_rapidgzip::{read_gz_into_fastq, Config, FastqChunk};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/adversarial")
        .join(name)
}

/// ~65 MiB of identical 256-base reads must decode correctly across both the
/// serial (1 thread) and parallel (4 thread) paths, even though the decoded
/// size far exceeds the 64 MiB speculative per-chunk reservation.
#[test]
fn expansion_past_speculative_reservation_decodes_correctly() {
    // Derived from gen.py: it writes 256-base reads until the uncompressed size
    // first reaches 65 MiB. 88_059 reads × 774 bytes = 68_157_666 bytes.
    const EXPECTED_READS: usize = 88_059;
    const BASE: u8 = b'A';

    let path = fixture("more_than_64_mb_after_expansion.fastq.gz");

    for threads in [1usize, 4] {
        let (tx, rx) = bounded::<FastqChunk>(8);
        let cfg = Config {
            num_threads: threads,
            ..Config::default()
        };
        let p = path.clone();
        let producer = thread::spawn(move || read_gz_into_fastq(&p, tx, cfg));

        let mut reads = 0usize;
        for c in rx {
            // seq/qual share one metadata column in the DualStringPod, so their
            // counts are structurally equal; assert names line up too.
            assert_eq!(c.names.len(), c.reads.len(), "names vs reads (t={threads})");
            let all_base = |bytes: &[u8]| bytes.len() == 256 && bytes.iter().all(|&b| b == BASE);
            for name in c.names.iter() {
                assert!(all_base(name), "name (t={threads})");
            }
            for seq in c.reads.iter_seq() {
                assert!(all_base(seq), "seq (t={threads})");
            }
            for qual in c.reads.iter_qual() {
                assert!(all_base(qual), "qual (t={threads})");
            }
            reads += c.reads.len();
        }
        producer
            .join()
            .expect("producer panicked")
            .expect("decode failed");
        assert_eq!(reads, EXPECTED_READS, "read count (t={threads})");
    }
}

/// A single read larger than u32::MAX must be rejected with a clear error, not
/// a panic in the StringPod `u32` position cast.
///
/// Heavy: decodes ~4 GiB before the offending line is assembled and needs
/// several GiB of RAM. Ignored by default; run with:
///
/// ```text
/// cargo test --release -p rusty-rapidgzip --test adversarial -- --ignored
/// ```
#[test]
#[ignore = "decodes ~4 GiB and needs several GiB of RAM; run with --ignored"]
fn read_exceeding_u32_fails_gracefully() {
    let path = fixture("4gb_plus_read.fastq.gz");

    let (tx, rx) = bounded::<FastqChunk>(8);
    let cfg = Config::default();
    let producer = thread::spawn(move || read_gz_into_fastq(&path, tx, cfg));

    // No whole record ever completes (the single read never terminates within
    // the limit), so the consumer simply drains until the sink closes.
    for _ in rx {}

    let err = producer
        .join()
        .expect("producer panicked")
        .expect_err("expected a graceful error, not success");
    assert!(
        err.to_string()
            .contains("FASTQ read length exceeds the allowed maximum of 4 GiB"),
        "unexpected error: {err}"
    );
}
